swagger: '2.0'
info:
  title: Code Highlighter
  description: Code Highlighter
  termsOfService: https://https://opensource.org/licenses/MIT
  contact:
    email: daviddamilola20@gmail.com
  license:
    name: MIT License
  version: v1
host: 127.0.0.1:8000
schemes:
  - http
basePath: /
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  Basic:
    type: basic
security:
  - Basic: []
paths:
  /snippets/:
    get:
      operationId: snippets_list
      summary: This viewset automatically provides `list`, `create`, `retrieve`, `update`
        and `destroy` actions
      description: Additionally we provide an extra `highlight` action
      parameters:
        - name: page
          in: query
          description: A page number within the paginated result set.
          required: false
          type: integer
      responses:
        '200':
          description: ''
          schema:
            required:
              - count
              - results
            type: object
            properties:
              count:
                type: integer
              next:
                type: string
                format: uri
                x-nullable: true
              previous:
                type: string
                format: uri
                x-nullable: true
              results:
                type: array
                items:
                  $ref: '#/definitions/Snippet'
      tags:
        - snippets
    post:
      operationId: snippets_create
      summary: This viewset automatically provides `list`, `create`, `retrieve`, `update`
        and `destroy` actions
      description: Additionally we provide an extra `highlight` action
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/Snippet'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/Snippet'
      tags:
        - snippets
    parameters: []
  /snippets/{id}/:
    get:
      operationId: snippets_read
      summary: This viewset automatically provides `list`, `create`, `retrieve`, `update`
        and `destroy` actions
      description: Additionally we provide an extra `highlight` action
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Snippet'
      tags:
        - snippets
    put:
      operationId: snippets_update
      summary: This viewset automatically provides `list`, `create`, `retrieve`, `update`
        and `destroy` actions
      description: Additionally we provide an extra `highlight` action
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/Snippet'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Snippet'
      tags:
        - snippets
    patch:
      operationId: snippets_partial_update
      summary: This viewset automatically provides `list`, `create`, `retrieve`, `update`
        and `destroy` actions
      description: Additionally we provide an extra `highlight` action
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/Snippet'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Snippet'
      tags:
        - snippets
    delete:
      operationId: snippets_delete
      summary: This viewset automatically provides `list`, `create`, `retrieve`, `update`
        and `destroy` actions
      description: Additionally we provide an extra `highlight` action
      parameters: []
      responses:
        '204':
          description: ''
      tags:
        - snippets
    parameters:
      - name: id
        in: path
        description: A unique integer value identifying this snippet.
        required: true
        type: integer
  /snippets/{id}/highlight/:
    get:
      operationId: snippets_highlight
      summary: This viewset automatically provides `list`, `create`, `retrieve`, `update`
        and `destroy` actions
      description: Additionally we provide an extra `highlight` action
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Snippet'
      produces: []
      tags:
        - snippets
    parameters:
      - name: id
        in: path
        description: A unique integer value identifying this snippet.
        required: true
        type: integer
  /users/:
    get:
      operationId: users_list
      description: This viewset automatically provides list and retrieve actions.
      parameters:
        - name: page
          in: query
          description: A page number within the paginated result set.
          required: false
          type: integer
      responses:
        '200':
          description: ''
          schema:
            required:
              - count
              - results
            type: object
            properties:
              count:
                type: integer
              next:
                type: string
                format: uri
                x-nullable: true
              previous:
                type: string
                format: uri
                x-nullable: true
              results:
                type: array
                items:
                  $ref: '#/definitions/User'
      tags:
        - users
    parameters: []
  /users/{id}/:
    get:
      operationId: users_read
      description: This viewset automatically provides list and retrieve actions.
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/User'
      tags:
        - users
    parameters:
      - name: id
        in: path
        description: A unique integer value identifying this user.
        required: true
        type: integer
definitions:
  Snippet:
    required:
      - code
    type: object
    properties:
      url:
        title: Url
        type: string
        format: uri
        readOnly: true
      id:
        title: ID
        type: integer
        readOnly: true
      highlight:
        title: Highlight
        type: string
        format: uri
        readOnly: true
      title:
        title: Title
        type: string
        maxLength: 100
      code:
        title: Code
        type: string
        minLength: 1
      linenos:
        title: Linenos
        type: boolean
      language:
        title: Language
        type: string
        enum:
          - abap
          - abnf
          - ada
          - adl
          - agda
          - aheui
          - ahk
          - alloy
          - ampl
          - antlr
          - antlr-as
          - antlr-cpp
          - antlr-csharp
          - antlr-java
          - antlr-objc
          - antlr-perl
          - antlr-python
          - antlr-ruby
          - apacheconf
          - apl
          - applescript
          - arduino
          - arrow
          - as
          - as3
          - aspectj
          - aspx-cs
          - aspx-vb
          - asy
          - at
          - augeas
          - autoit
          - awk
          - bare
          - basemake
          - bash
          - bat
          - bbcbasic
          - bbcode
          - bc
          - befunge
          - bib
          - blitzbasic
          - blitzmax
          - bnf
          - boa
          - boo
          - boogie
          - brainfuck
          - bst
          - bugs
          - c
          - c-objdump
          - ca65
          - cadl
          - camkes
          - capdl
          - capnp
          - cbmbas
          - ceylon
          - cfc
          - cfengine3
          - cfm
          - cfs
          - chai
          - chapel
          - charmci
          - cheetah
          - cirru
          - clay
          - clean
          - clojure
          - clojurescript
          - cmake
          - cobol
          - cobolfree
          - coffee-script
          - common-lisp
          - componentpascal
          - console
          - control
          - coq
          - cpp
          - cpp-objdump
          - cpsa
          - cr
          - crmsh
          - croc
          - cryptol
          - csharp
          - csound
          - csound-document
          - csound-score
          - css
          - css+django
          - css+erb
          - css+genshitext
          - css+lasso
          - css+mako
          - css+mozpreproc
          - css+myghty
          - css+php
          - css+smarty
          - cucumber
          - cuda
          - cypher
          - cython
          - d
          - d-objdump
          - dart
          - dasm16
          - delphi
          - devicetree
          - dg
          - diff
          - django
          - docker
          - doscon
          - dpatch
          - dtd
          - duel
          - dylan
          - dylan-console
          - dylan-lid
          - earl-grey
          - easytrieve
          - ebnf
          - ec
          - ecl
          - eiffel
          - elixir
          - elm
          - emacs
          - email
          - erb
          - erl
          - erlang
          - evoque
          - execline
          - extempore
          - ezhil
          - factor
          - fan
          - fancy
          - felix
          - fennel
          - fish
          - flatline
          - floscript
          - forth
          - fortran
          - fortranfixed
          - foxpro
          - freefem
          - fsharp
          - fstar
          - gap
          - gas
          - gdscript
          - genshi
          - genshitext
          - glsl
          - gnuplot
          - go
          - golo
          - gooddata-cl
          - gosu
          - groff
          - groovy
          - gst
          - haml
          - handlebars
          - haskell
          - haxeml
          - hexdump
          - hlsl
          - hsail
          - hspec
          - html
          - html+cheetah
          - html+django
          - html+evoque
          - html+genshi
          - html+handlebars
          - html+lasso
          - html+mako
          - html+myghty
          - html+ng2
          - html+php
          - html+smarty
          - html+twig
          - html+velocity
          - http
          - hx
          - hybris
          - hylang
          - i6t
          - icon
          - idl
          - idris
          - iex
          - igor
          - inform6
          - inform7
          - ini
          - io
          - ioke
          - irc
          - isabelle
          - j
          - jags
          - jasmin
          - java
          - javascript+mozpreproc
          - jcl
          - jlcon
          - js
          - js+cheetah
          - js+django
          - js+erb
          - js+genshitext
          - js+lasso
          - js+mako
          - js+myghty
          - js+php
          - js+smarty
          - jsgf
          - json
          - jsonld
          - jsp
          - julia
          - juttle
          - kal
          - kconfig
          - kmsg
          - koka
          - kotlin
          - lagda
          - lasso
          - lcry
          - lean
          - less
          - lhs
          - lidr
          - lighty
          - limbo
          - liquid
          - live-script
          - llvm
          - llvm-mir
          - llvm-mir-body
          - logos
          - logtalk
          - lsl
          - lua
          - make
          - mako
          - maql
          - mask
          - mason
          - mathematica
          - matlab
          - matlabsession
          - md
          - mime
          - minid
          - modelica
          - modula2
          - monkey
          - monte
          - moocode
          - moon
          - mosel
          - mozhashpreproc
          - mozpercentpreproc
          - mql
          - ms
          - mscgen
          - mupad
          - mxml
          - myghty
          - mysql
          - nasm
          - ncl
          - nemerle
          - nesc
          - newlisp
          - newspeak
          - ng2
          - nginx
          - nim
          - nit
          - nixos
          - notmuch
          - nsis
          - numpy
          - nusmv
          - objdump
          - objdump-nasm
          - objective-c
          - objective-c++
          - objective-j
          - ocaml
          - octave
          - odin
          - ooc
          - opa
          - openedge
          - pacmanconf
          - pan
          - parasail
          - pawn
          - peg
          - perl
          - perl6
          - php
          - pig
          - pike
          - pkgconfig
          - plpgsql
          - pointless
          - pony
          - postgresql
          - postscript
          - pot
          - pov
          - powershell
          - praat
          - prolog
          - promql
          - properties
          - protobuf
          - ps1con
          - psql
          - psysh
          - pug
          - puppet
          - py2tb
          - pycon
          - pypylog
          - pytb
          - python
          - python2
          - qbasic
          - qml
          - qvto
          - racket
          - ragel
          - ragel-c
          - ragel-cpp
          - ragel-d
          - ragel-em
          - ragel-java
          - ragel-objc
          - ragel-ruby
          - raw
          - rb
          - rbcon
          - rconsole
          - rd
          - reason
          - rebol
          - red
          - redcode
          - registry
          - resource
          - rexx
          - rhtml
          - ride
          - rnc
          - roboconf-graph
          - roboconf-instances
          - robotframework
          - rql
          - rsl
          - rst
          - rts
          - rust
          - sarl
          - sas
          - sass
          - sc
          - scala
          - scaml
          - scdoc
          - scheme
          - scilab
          - scss
          - sgf
          - shen
          - shexc
          - sieve
          - silver
          - singularity
          - slash
          - slim
          - slurm
          - smali
          - smalltalk
          - smarty
          - sml
          - snobol
          - snowball
          - solidity
          - sourceslist
          - sp
          - sparql
          - spec
          - splus
          - sql
          - sqlite3
          - squidconf
          - ssp
          - stan
          - stata
          - swift
          - swig
          - systemverilog
          - tads3
          - tap
          - tasm
          - tcl
          - tcsh
          - tcshcon
          - tea
          - termcap
          - terminfo
          - terraform
          - tex
          - text
          - thrift
          - tid
          - tnt
          - todotxt
          - toml
          - trac-wiki
          - treetop
          - ts
          - tsql
          - ttl
          - turtle
          - twig
          - typoscript
          - typoscriptcssdata
          - typoscripthtmldata
          - ucode
          - unicon
          - urbiscript
          - usd
          - vala
          - vb.net
          - vbscript
          - vcl
          - vclsnippets
          - vctreestatus
          - velocity
          - verilog
          - vgl
          - vhdl
          - vim
          - wdiff
          - webidl
          - whiley
          - x10
          - xml
          - xml+cheetah
          - xml+django
          - xml+erb
          - xml+evoque
          - xml+lasso
          - xml+mako
          - xml+myghty
          - xml+php
          - xml+smarty
          - xml+velocity
          - xorg.conf
          - xquery
          - xslt
          - xtend
          - xul+mozpreproc
          - yaml
          - yaml+jinja
          - yang
          - zeek
          - zephir
          - zig
      style:
        title: Style
        type: string
        enum:
          - abap
          - algol
          - algol_nu
          - arduino
          - autumn
          - borland
          - bw
          - colorful
          - default
          - emacs
          - friendly
          - fruity
          - igor
          - inkpot
          - lovelace
          - manni
          - monokai
          - murphy
          - native
          - paraiso-dark
          - paraiso-light
          - pastie
          - perldoc
          - rainbow_dash
          - rrt
          - sas
          - solarized-dark
          - solarized-light
          - stata
          - stata-dark
          - stata-light
          - tango
          - trac
          - vim
          - vs
          - xcode
      owner:
        title: Owner
        type: string
        readOnly: true
  User:
    required:
      - username
    type: object
    properties:
      url:
        title: Url
        type: string
        format: uri
        readOnly: true
      id:
        title: ID
        type: integer
        readOnly: true
      username:
        title: Username
        description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
          only.
        type: string
        pattern: ^[\w.@+-]+$
        maxLength: 150
        minLength: 1
      snippets:
        type: array
        items:
          type: string
          format: uri
        readOnly: true
        uniqueItems: true
